export const FETCH_POSTS = 'FETCH_POSTS';
export const NEW_POST  = 'NEW_POST';

export const CLICK_SEARCH_BAR = 'CLICK_SEARECH_BAR';
export const OUT_CLICK_SEARCH_BAR = 'OUT_CLICK_SEARECH_BAR';
export const CLICK_CATEGORY = 'CLICK_CATEGORY';

export const CHANGE_FOCUS = 'CHANGE_FOCUS';
export const TYPING_SEARCH_QUERY = 'TYPING_SEARCH_QUERY';

export const UPDATE_SEARCHED_RESULT = 'UPDATE_SEARCHED_RESULT';
export const SAVE_RECENT_SEARCH_RESULT = 'SAVE_RECENT_SEARCH_RESULT';
export const SELECT_SEARCHED_ITEM = 'SELECT_SEARCHED_ITEM';
export const GO_SEARCH_RESULT = 'GO_SEARCH_RESULT';

//routing page action
export const CHANGE_PAGE_PATH = 'CHANGE_PAGE_PATH';

//search filter option
export const CHANAGE_SEARCH_FITLER_OTPTION = 'CHANAGE_SEARCH_FITLER_OTPTION';

export const OUT_CLICK_FILER_PANEL = 'OUT_CLICK_FILER_PANEL';


//alert system acton
export const CLICK_CLOSE_BUTTON = 'CLICK_CLOSE_BUTTON';

export const ON_HOVER_ITEM = 'ON_HOVER_ITEM';
export const SAVE_SERCH_RESULT = 'SAVE_SERCH_RESULT';


export const CHANAGE_SEARCH_NEWS_FITLER_OTPTION = 'CHANAGE_SEARCH_NEWS_FITLER_OTPTION';
